coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%

ignore:
  - "**/*.stories.tsx"
  - "**/*.stories.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "tests/**/*"
  - "node_modules/**/*"
  - ".next/**/*"
